insert into album_song (album_song_id, title, genre, rate) values (1, 'Wild', 'metal', 0);
insert into album_song (album_song_id, title, genre, rate) values (2, 'Ghoulies III: Ghoulies Go to College', 'rap', 6);
insert into album_song (album_song_id, title, genre, rate) values (3, 'Three Kingdoms: Resurrection of the Dragon', 'arabesque', 2);
insert into album_song (album_song_id, title, genre, rate) values (4, 'Amazon Jack 2: The Movie Star', 'hip-hop', 3);
insert into album_song (album_song_id, title, genre, rate) values (5, 'Profound Desires of the Gods (Kamigami no fukaki yokubo) ', 'folk', 2);
insert into album_song (album_song_id, title, genre, rate) values (6, 'Wuthering Heights', 'country', 9);
insert into album_song (album_song_id, title, genre, rate) values (7, 'Far Off Place, A', 'jazz', 2);
insert into album_song (album_song_id, title, genre, rate) values (8, 'All the Right Moves', 'blues', 5);
insert into album_song (album_song_id, title, genre, rate) values (9, 'Ice Age: Dawn of the Dinosaurs', 'rap', 5);
insert into album_song (album_song_id, title, genre, rate) values (10, 'Cinderella', 'folk', 7);
insert into album_song (album_song_id, title, genre, rate) values (11, 'Alice and Martin (Alice et Martin)', 'arabesque', 3);
insert into album_song (album_song_id, title, genre, rate) values (12, 'Jacqueline Susann''s Once Is Not Enough', 'jazz', 8);
insert into album_song (album_song_id, title, genre, rate) values (13, 'Around the World Under the Sea', 'hip-hop', 6);
insert into album_song (album_song_id, title, genre, rate) values (14, 'Monsieur Verdoux', 'blues', 8);
insert into album_song (album_song_id, title, genre, rate) values (15, 'Grey, The', 'country', 7);
insert into album_song (album_song_id, title, genre, rate) values (16, 'Heaven''s Burning', 'metal', 4);
insert into album_song (album_song_id, title, genre, rate) values (17, 'Descendant of the Sun (Ri jie)', 'jazz', 1);
insert into album_song (album_song_id, title, genre, rate) values (18, 'Psycho', 'rap', 3);
insert into album_song (album_song_id, title, genre, rate) values (19, 'All the Boys Love Mandy Lane', 'arabesque', 8);
insert into album_song (album_song_id, title, genre, rate) values (20, 'Gentle Woman, A (Une femme douce)', 'folk', 3);
insert into album_song (album_song_id, title, genre, rate) values (21, 'Born into Brothels', 'blues', 2);
insert into album_song (album_song_id, title, genre, rate) values (22, 'Devil''s Rock, The', 'country', 6);
insert into album_song (album_song_id, title, genre, rate) values (23, 'Appeared, The (Aparecidos)', 'hip-hop', 3);
insert into album_song (album_song_id, title, genre, rate) values (24, 'Down and Derby', 'metal', 0);
insert into album_song (album_song_id, title, genre, rate) values (25, 'Unmistaken Child', 'jazz', 4);
insert into album_song (album_song_id, title, genre, rate) values (26, 'Twist of Faith', 'rap', 4);
insert into album_song (album_song_id, title, genre, rate) values (27, 'Enemy Within, The (O ehthros mou)', 'arabesque', 3);
insert into album_song (album_song_id, title, genre, rate) values (28, 'Kronos', 'folk', 7);
insert into album_song (album_song_id, title, genre, rate) values (29, 'Geography Club', 'blues', 8);
insert into album_song (album_song_id, title, genre, rate) values (30, 'Last Kiss, The (Ultimo bacio, L'')', 'country', 9);
insert into album_song (album_song_id, title, genre, rate) values (31, 'Operation Daybreak', 'hip-hop', 2);
insert into album_song (album_song_id, title, genre, rate) values (32, 'The Third Reich: The Rise & Fall', 'metal', 1);
insert into album_song (album_song_id, title, genre, rate) values (33, 'German Doctor, The (Wakolda)', 'jazz', 3);
insert into album_song (album_song_id, title, genre, rate) values (34, 'Anywhere But Here', 'rap', 3);
insert into album_song (album_song_id, title, genre, rate) values (35, 'Rapture-Palooza', 'arabesque', 3);
insert into album_song (album_song_id, title, genre, rate) values (36, 'Kid Stays in the Picture, The', 'folk', 4);
insert into album_song (album_song_id, title, genre, rate) values (37, 'Girl Crazy', 'blues', 6);
insert into album_song (album_song_id, title, genre, rate) values (38, 'Psycho', 'country', 6);
insert into album_song (album_song_id, title, genre, rate) values (39, 'Better This World', 'hip-hop', 7);
insert into album_song (album_song_id, title, genre, rate) values (40, 'Le convoyeur', 'metal', 1);