insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (1, '01-06-1991', null, 15, 5);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (2, null, 'CASH', 10, 13);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (3, '11-03-1991', 'CREDIT CARD', 9, 1);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (4, null, 'CASH', 16, 5);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (5, '11-04-1991', 'CASH', 17, 7);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (6, '08-08-1991', 'CREDIT CARD', 3, 14);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (7, '12-01-1992', 'CASH', 17, 12);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (8, '03-08-1992', 'CREDIT CARD', 7, 1);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (9, '05-01-1991', 'CASH', 7, 5);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (10, '06-08-1992', 'CASH', 16, 1);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (11, null, 'Julie', 9, 6);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (12, '03-09-1992', 'CASH', 7, 13);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (13, null, 'Abram', 15, 2);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (14, '12-07-1992', 'CASH', 11, 15);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (15, '11-06-1992', 'CREDIT CARD', 18, 19);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (16, '05-02-1992', 'CASH', 3, 4);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (17, '02-04-1991', 'CASH', 5, 4);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (18, '04-01-1992', 'CREDIT CARD', 16, 4);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (19, '10-03-1991', 'CASH', 1, 16);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (20, null, 'CREDIT CARD', 20, 10);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (21, '05-02-1992', 'CASH', 3, 4);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (22, '02-04-1991', 'CASH', 5, 4);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (23, '04-01-1992', 'CREDIT CARD', 16, 4);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (24, '10-03-1991', 'CASH', 1, 16);
insert into sale (sale_id, sale_date, payment_method, customer_id, staff_id) values (25, null, 'CREDIT CARD', 20, 10);